[package]
name = "shortcutd"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
evdev = "0.10.1"
main_error = "0.1.0"
num_enum = "0.4.3"
dbus = "0.8.2"
parse-display = "0.1.1"